openapi: 3.0.1

info:
  title: Aegir API
  description: API of the Aegir mash controller
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

paths:
  /:
    get:
      operationId: api.go_home
      responses:
        200:
          description: Successfully loaded html page.
          content:
            text/html:
              schema:
                type: string

  /service-worker.js:
    get:
      operationId: api.get_service_worker_js
      responses:
        200:
          description: successful operation
          content:
            text/javascript:
              schema:
                type: string

  /manifest.json:
    get:
      operationId: api.get_manifest_json
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string

  /img/{filename}:
    get:
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      operationId: api.get_img_file
      responses:
        200:
          description: successful operation
          content:
            text/javascript:
              schema:
                type: string

  /js/{filename}:
    get:
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      operationId: api.get_js_file
      responses:
        200:
          description: successful operation
          content:
            text/javascript:
              schema:
                type: string

  /api/time:
    get:
      operationId: api.device_time_get
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: number

  /api/temperature:
    get:
      operationId: api.temperature_get
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: number

  /api/temperature/history:
    get:
      operationId: api.temperature_history_get
      parameters:
        - name: minutes
          in: query
          description: Return only the last N minutes of data
          required: false
          style: simple
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: dict

  /api/weight/calibrate:
    post:
      operationId: api.weight_calibrate
      requestBody:
        description: Calibrate scale with a known weight
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                value:
                  type: number
              required:
                - value
      responses:
        200:
          description: successful operation

  /api/weight:
    get:
      operationId: api.weight_get
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: number
    post:
      operationId: api.weight_set
      responses:
        200:
          description: successful operation
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  value:
                    type: number
                required:
                  - value

  /api/weight/history:
    get:
      operationId: api.weight_history_get
      parameters:
        - name: minutes
          in: query
          description: Return only the last N minutes of data
          required: false
          style: simple
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: dict

  /push/subscription:
    put:
      operationId: api.push_add_subscription
      requestBody:
        description: Notification subscription
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: successful operation

  /push:
    post:
      operationId: api.push_message
      requestBody:
        description: Notification message (debug)
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: successful operation
